"""Additional bilingual conversation guides for DilSe's Pakistan content library."""

ADDITIONAL_TOPICS = {
    "silent-treatment": {
        "title": "How to Respond to the Silent Treatment in Marriage | DilSe Pakistan",
        "heading": "Respond when silence replaces the conversation",
        "description": "Prepare a calm response when your husband or partner stops speaking after a disagreement.",
        "intro": "Time to cool down can help a difficult conversation, but unexplained silence leaves the other person guessing about what happened and when communication will resume. Ask for a clear pause, a return time and a basic level of practical communication while emotions settle.",
        "situations": ["Your partner stops replying for hours or days after a disagreement.", "Necessary questions about children, transport or bills are also ignored.", "You keep apologising or sending messages because you do not know when the silence will end."],
        "prepare": ["Distinguish a stated cooling-off period from silence with no explanation or return time.", "Choose one recent incident and describe its practical effect.", "Ask for a pause sentence and a specific time to resume the discussion."],
        "gentle": "Agar tumhein waqt chahiye to main space de sakti hoon. Bas mujhe bata do ke hum is baat par kab wapas aayenge, taa ke main andaza na lagati rahoon.",
        "direct": "Do din tak jawab na milne se masla solve nahi hota. Agar ab baat nahi karni to ek waqt decide karo. Zaroori ghar ke sawalon ka jawab phir bhi chahiye.",
        "responses": [("Mujhe akela chhor do.", "Theek hai. Main ab space de rahi hoon. Mujhe sirf yeh confirm karna hai ke hum kal raat aath baje baat karenge."), ("Tum baat ko kheench rahi ho.", "Main abhi behas nahi kar rahi. Main sirf yeh chahti hoon ke pause ka end time clear ho.")],
        "progress": ["Either partner can request space without disappearing indefinitely.", "A return time is stated and kept.", "Essential household communication continues during the pause."],
        "related": ["talking-without-argument", "emotional-connection", "disrespectful-conversations"],
        "urdu": "khamoshi-se-saza",
        "image_alt": "Pakistani woman calmly asking her husband when they can resume a paused conversation",
    },
    "separate-from-joint-family": {
        "title": "How to Discuss Living Separately From a Joint Family | DilSe Pakistan",
        "heading": "Discuss a separate home without insulting the family",
        "description": "Prepare a practical conversation about moving out of a joint family home in Pakistan.",
        "intro": "A request for a separate home can be heard as rejection of parents or relatives. Keep the discussion focused on the couple's daily needs, finances, care responsibilities and the relationship you want to maintain with both families.",
        "situations": ["There is no reliable privacy for the couple or children.", "Repeated household conflict is affecting the marriage.", "One partner wants to move but the other fears family blame or added expense."],
        "prepare": ["List the daily problems a separate home would address without attacking individual relatives.", "Prepare a realistic budget, location and plan for supporting parents.", "Decide whether you are asking for a trial period, a target date or a first planning discussion."],
        "gentle": "Main family se rishta kam nahi karna chahti. Main chahti hoon ke hum alag ghar ke option ko budget aur daily routine ke saath dekhein, taa ke hamari privacy aur family support dono manage ho saken.",
        "direct": "Ghar ki current situation hamari marriage ko roz affect kar rahi hai. Main chahti hoon ke hum is mahine alag rehne ka budget aur timeline banayein.",
        "responses": [("Tum meri family todna chahti ho.", "Main family se rishta khatam karne ki baat nahi kar rahi. Main residence aur relationship ko alag decisions ke taur par dekhna chahti hoon."), ("Hum afford nahi kar sakte.", "Chalo actual rent, bills aur transport likhte hain. Agar ab possible nahi to savings target aur review date decide karte hain.")],
        "progress": ["The couple compares real costs instead of arguing only about loyalty.", "Support for parents and visits are included in the plan.", "A decision or review date is recorded."],
        "related": ["joint-family-privacy", "family-boundaries", "money-conversations"],
        "urdu": "joint-family-se-alag",
        "image_alt": "Pakistani couple comparing a household budget while discussing a separate home",
    },
    "sharing-private-matters": {
        "title": "When Your Husband Shares Private Matters With Family | DilSe Pakistan",
        "heading": "Ask before private matters are shared with family",
        "description": "Prepare a conversation about keeping marital disagreements and personal information private.",
        "intro": "Seeking support from family can be reasonable, but sharing a partner's health, finances or private disagreement without consent can damage trust. Define which information needs agreement before either person shares it.",
        "situations": ["A private disagreement is repeated to parents or siblings.", "Personal health or financial information is shared without permission.", "Relatives enter the conflict with only one partner's version of events."],
        "prepare": ["Name the information that was shared and how you learned about it.", "Explain the effect without demanding that your partner never seek support.", "Propose categories that are private, shareable or require agreement first."],
        "gentle": "Main samajhti hoon ke kabhi family se support chahiye hoti hai. Meri personal baat share karne se pehle main chahti hoon ke tum mujh se poochho.",
        "direct": "Hamari kal ki disagreement meri permission ke baghair share hui. Ab se health, paisay aur hamare conflicts ki detail pehle agree kiye baghair share na ho.",
        "responses": [("Main apni family se kuch bhi share kar sakta hoon.", "Tum support le sakte ho, lekin meri personal information bhi involved hai. Humein dono ki privacy ka rule chahiye."), ("Unhon ne sirf mashwara diya.", "Masla mashwaray ka nahi, detail share karne se pehle consent ka hai.")],
        "progress": ["Both partners know which topics need consent before sharing.", "A trusted support person can be chosen without disclosing unnecessary details.", "Relatives are not asked to settle routine couple disagreements."],
        "related": ["family-boundaries", "joint-family-privacy", "trust-and-privacy"],
        "urdu": "zaati-baat-family-se-share",
        "image_alt": "Pakistani couple agreeing which personal matters should remain private",
    },
    "supporting-parents-financially": {
        "title": "How to Discuss Financial Support for Parents After Marriage | DilSe Pakistan",
        "heading": "Plan support for parents without hiding household costs",
        "description": "Discuss regular financial support for parents while protecting bills, savings and shared decisions.",
        "intro": "Supporting parents may be a firm responsibility and an expression of care. Conflict grows when the amount, timing or effect on household commitments is hidden. Put the figures together and agree which changes require another discussion.",
        "situations": ["Money is sent to parents before essential household bills are covered.", "One family receives support while the other partner's parents are excluded without discussion.", "Emergency requests repeatedly replace the agreed monthly amount."],
        "prepare": ["List income, fixed expenses, debt, savings and current family support.", "Separate regular support from genuine emergencies.", "Agree on an amount or percentage and a threshold for discussing extra help."],
        "gentle": "Main dono taraf ke parents ki zaroorat ko respect karti hoon. Kya hum bills ke baad regular support ka amount aur emergency ke liye rule mil kar decide kar sakte hain?",
        "direct": "Is mahine support bhejne ke baad rent short hua. Main chahti hoon ke regular amount budget mein ho aur extra transfer se pehle hum dono baat karein.",
        "responses": [("Parents ka haq discuss nahi hota.", "Main unka haq deny nahi kar rahi. Main amount aur timing ko household commitments ke saath plan karna chahti hoon."), ("Tum apni family ko zyada importance deti ho.", "Chalo dono taraf ki actual needs aur available amount ek hi table mein dekhein.")],
        "progress": ["Regular support appears in the monthly budget.", "Both families are discussed using the same criteria.", "Extra requests have an agreed decision process."],
        "related": ["money-conversations", "family-boundaries", "household-responsibilities"],
        "urdu": "walidain-ki-mali-madad",
        "image_alt": "Pakistani couple planning household expenses and financial support for parents",
    },
    "children-education": {
        "title": "How to Discuss Children's Education With Your Spouse | DilSe Pakistan",
        "heading": "Make education decisions using the same information",
        "description": "Prepare a conversation about school choice, fees, tutoring, language and expectations for children.",
        "intro": "Education decisions combine money, values, travel time and a child's needs. Compare the available options against agreed criteria instead of treating one school, curriculum or result as proof of good parenting.",
        "situations": ["Partners disagree about public, private or religious schooling.", "Fees or tutoring costs are creating pressure on the household budget.", "One parent wants stricter academic expectations while the other is worried about the child's stress."],
        "prepare": ["Collect the same information on fees, travel, class size and admissions.", "Ask what each parent wants the child to gain and what they are worried about.", "Include the child's observed needs without asking the child to choose between parents."],
        "gentle": "Hum dono bachay ke liye acha chahte hain. Kya hum school options ko fees, distance aur uski learning needs ke hisaab se compare kar sakte hain?",
        "direct": "Admission deadline qareeb hai aur abhi criteria clear nahi. Main chahti hoon ke hum Friday tak options likh kar decision karein.",
        "responses": [("Best school ke liye sacrifice karna parta hai.", "Main effort se agree karti hoon. Humein yeh bhi dekhna hai ke fee har month sustainable hai ya nahi."), ("Tum bachay par pressure nahi dalna chahti.", "Main expectations khatam nahi kar rahi. Main aisi routine chahti hoon jo learning aur wellbeing dono ko support kare.")],
        "progress": ["Options are compared using shared criteria.", "Costs and daily transport have named owners.", "The decision includes a date to review how the child is coping."],
        "related": ["money-conversations", "household-responsibilities", "talking-without-argument"],
        "urdu": "bachon-ki-taleem",
        "image_alt": "Pakistani parents reviewing school information and education costs together",
    },
    "moving-city-or-abroad": {
        "title": "How to Discuss Moving Abroad or to Another City | DilSe Pakistan",
        "heading": "Turn a possible move into decisions you can compare",
        "description": "Discuss relocation, immigration, work, parents and children's needs with your spouse.",
        "intro": "A move can change income, careers, childcare, care for parents and access to support. Before debating the whole future, identify what is confirmed, what remains uncertain and what each partner would be giving up.",
        "situations": ["One partner receives a job offer in another city or country.", "The couple is considering immigration but disagrees about timing or risk.", "Parents need care and the proposed move would reduce nearby support."],
        "prepare": ["Separate confirmed details from estimates about salary, visas, housing and timing.", "List the effect on both careers, children and care for parents.", "Decide which missing information must be obtained before a final answer."],
        "gentle": "Yeh move hum dono ki daily life badlega. Kya hum income ke saath meri work, bachon aur parents ki care bhi ek plan mein likh sakte hain?",
        "direct": "Main confirmed plan ke baghair move ka final jawab nahi de sakti. Humein housing, visa, meri work aur parents ki support clear karni hai.",
        "responses": [("Aisa chance dobara nahi milega.", "Deadline real hai, lekin decision ke effects bhi real hain. Chalo deadline se pehle missing facts collect karte hain."), ("Tum meri progress rok rahi ho.", "Main opportunity reject nahi kar rahi. Main chahti hoon ke plan dono partners ke costs ko include kare.")],
        "progress": ["Facts and assumptions are listed separately.", "The plan includes both partners' work and care responsibilities.", "The couple has a decision date and a fallback if the move does not proceed."],
        "related": ["career-after-marriage", "supporting-parents-financially", "money-conversations"],
        "urdu": "shehar-ya-mulk-tabdeeli",
        "image_alt": "Pakistani couple discussing relocation plans with documents and a map",
    },
    "social-media-boundaries": {
        "title": "How to Set Social Media Boundaries in Marriage | DilSe Pakistan",
        "heading": "Agree what stays private on WhatsApp and social media",
        "description": "Discuss posting photos, online friendships, status updates and family WhatsApp groups with your spouse.",
        "intro": "Couples may have different ideas about what can be posted, forwarded or discussed online. Agree on the behaviour that needs consent, rather than using access to every account as the only measure of trust.",
        "situations": ["A photo or private update is posted without permission.", "Messages are forwarded to a family group during a disagreement.", "Partners disagree about online friendships, comments or public relationship posts."],
        "prepare": ["Name the exact post, message or interaction instead of judging all online activity.", "Separate public posting, private messaging and account access.", "Propose a consent rule that applies equally to both partners."],
        "gentle": "Meri photo ya personal update post karne se pehle main chahti hoon ke hum ek doosre se poochhein. Kya yeh rule hum dono ke liye rakh sakte hain?",
        "direct": "Hamari private chat family group mein forward hui. Main is par razi nahi thi. Ab se private messages consent ke baghair forward na hon.",
        "responses": [("Social media ko itna serious kyun leti ho?", "Post online reh sakti hai aur doosre log share kar sakte hain. Is liye consent mere liye serious hai."), ("Password do phir trust hoga.", "Main concern discuss karungi, lekin passwords aur specific behaviour do alag questions hain.")],
        "progress": ["Both partners ask before posting personal information or images.", "Private messages are not forwarded without consent.", "Online concerns are raised using a specific example rather than constant monitoring."],
        "related": ["trust-and-privacy", "sharing-private-matters", "family-boundaries"],
        "urdu": "social-media-hudood",
        "image_alt": "Pakistani couple agreeing on privacy settings for WhatsApp and social media",
    },
    "rebuilding-trust-after-secrecy": {
        "title": "How to Rebuild Trust After Something Was Hidden | DilSe Pakistan",
        "heading": "Ask for repair after secrecy or a lie",
        "description": "Prepare a conversation after hidden spending, messages, plans or another breach of trust.",
        "intro": "Trust is not restored by demanding instant belief or permanent surveillance. The conversation needs a clear account of what happened, acknowledgement of the effect and a limited repair plan connected to the actual breach.",
        "situations": ["Spending, debt or a financial commitment was hidden.", "Messages or contact with someone were denied and later discovered.", "A major plan was kept secret until the decision was difficult to change."],
        "prepare": ["State what you know and what still needs a direct answer.", "Decide which repair action is connected to the breach.", "Avoid making promises about forgiveness before you have enough information."],
        "gentle": "Jo baat chhupayi gayi us se mera trust affect hua hai. Main pehle poori timeline samajhna chahti hoon, phir hum repair ke practical steps decide kar sakte hain.",
        "direct": "Mujhe facts aur clear answer chahiye. Main unlimited checking nahi chahti, lekin is specific issue ke liye agreed transparency aur review date chahiye.",
        "responses": [("Ab bata diya, ab aur kya chahiye?", "Batana pehla step hai. Mujhe impact acknowledge karna aur repeat na hone ka practical plan bhi chahiye."), ("Tum kabhi trust nahi karogi.", "Main future ka final decision abhi nahi de rahi. Main dekhna chahti hoon ke agreed actions consistently follow hote hain ya nahi.")],
        "progress": ["Questions receive consistent answers without changing the story.", "Repair actions match the specific breach and have a review date.", "Neither partner treats permanent surveillance as the only solution."],
        "related": ["trust-and-privacy", "money-conversations", "talking-without-argument"],
        "urdu": "baat-chhupane-ke-baad-bharosa",
        "image_alt": "Pakistani couple having a serious conversation about rebuilding trust",
    },
    "disrespectful-conversations": {
        "title": "What to Say When Conversations Become Disrespectful | DilSe Pakistan",
        "heading": "Set a limit when disagreement becomes disrespectful",
        "description": "Prepare words for insults, ridicule, repeated interruption or humiliation during an argument.",
        "intro": "A disagreement can continue without insults, threats or humiliation. State the behaviour you will not continue with, end the current exchange if needed and name the condition for returning to the topic.",
        "situations": ["A concern is answered with insults, mocking or character attacks.", "Private disagreements are turned into jokes in front of relatives.", "One partner repeatedly interrupts or refuses to let the other finish a sentence."],
        "prepare": ["Choose the exact words or behaviour you are addressing.", "Plan one short boundary sentence that you can repeat.", "Choose a safe way to leave or seek support if the behaviour escalates."],
        "gentle": "Main is issue par baat karna chahti hoon, lekin insult ke saath nahi. Agar hum dono normal tone mein baat kar saken to main continue karungi.",
        "direct": "Mujhe naam se bulaya ja raha hai. Main yeh conversation ab rok rahi hoon. Is topic par tab wapas aungi jab baat insult ke baghair ho.",
        "responses": [("Mazaaq bhi nahi samajh aata.", "Mujhe woh mazaaq humiliating laga. Main keh rahi hoon ke yeh mere bare mein doosron ke samne repeat na ho."), ("Tum bhi to karti ho.", "Agar meri specific baat disrespectful thi to usay next discuss karenge. Abhi main is behaviour ki boundary clear kar rahi hoon.")],
        "progress": ["The issue is discussed without insults or public humiliation.", "A pause is respected when either person is no longer speaking safely.", "Repeated intimidation is treated as a safety concern, not only a communication problem."],
        "related": ["talking-without-argument", "pausing-when-shouting", "silent-treatment"],
        "urdu": "be-izzati-wali-guftagu",
        "image_alt": "Pakistani woman calmly ending a disrespectful conversation and stepping away",
    },
    "asking-for-emotional-support": {
        "title": "How to Ask Your Husband for Emotional Support | DilSe Pakistan",
        "heading": "Ask to be heard before receiving advice",
        "description": "Prepare a clear request for listening, reassurance or practical help from your husband or partner.",
        "intro": "A partner may offer solutions when you want attention, reassurance or space to explain. Say what kind of response would help before describing the problem, and keep the request small enough to act on now.",
        "situations": ["Your concern receives immediate advice before you finish explaining.", "A worry is dismissed because there is no obvious practical solution.", "You need comfort but your partner assumes you are asking them to fix the situation."],
        "prepare": ["Decide whether you want listening, reassurance, advice or practical help.", "Choose a realistic amount of uninterrupted time.", "Say whether you want ideas after you have finished speaking."],
        "gentle": "Mujhe abhi solution se pehle das minute sirf sunne ki zaroorat hai. Kya tum meri baat complete hone tak sun sakte ho?",
        "direct": "Jab meri baat ke beech solution milta hai to mujhe lagta hai meri baat suni nahi gayi. Pehle mujhe finish karne do, phir main advice poochungi.",
        "responses": [("Main help hi to kar raha hoon.", "Mujhe pata hai. Is waqt sab se useful help yeh hogi ke tum pehle meri poori baat suno."), ("Is mein upset hone wali kya baat hai?", "Ho sakta hai tum isay different dekho. Main abhi apna experience explain karna chahti hoon, debate nahi.")],
        "progress": ["The requested type of support is stated clearly.", "The listener checks whether advice is wanted.", "Both partners can ask for a short conversation without promising to solve everything."],
        "related": ["emotional-connection", "talking-without-argument", "intimacy-and-affection"],
        "urdu": "jazbati-support-mangna",
        "image_alt": "Pakistani husband listening attentively while his wife explains a concern",
    },
    "visiting-families-fairly": {
        "title": "How to Discuss Visits to Both Families After Marriage | DilSe Pakistan",
        "heading": "Plan family visits without measuring loyalty",
        "description": "Discuss time with both families, Eid plans, travel and expectations after marriage.",
        "intro": "Visits can carry expectations about respect and belonging, especially around Eid, weddings and illness. Use the calendar, travel time and current family needs to agree on a plan instead of comparing which family matters more.",
        "situations": ["Most weekends or holidays are automatically assigned to one family.", "A partner is criticised for wanting time with her parents.", "Eid, weddings or illness create overlapping expectations."],
        "prepare": ["List the actual dates, travel time and commitments for the next month.", "Identify occasions that cannot move and visits that can be alternated.", "Agree on how the couple will communicate the plan to relatives."],
        "gentle": "Dono families hamare liye important hain. Kya hum aglay mahine ka calendar dekh kar visits pehle decide kar sakte hain?",
        "direct": "Pichlay chaar weekends ek hi taraf gaye. Main chahti hoon ke is month meri family ke liye bhi do dates abhi reserve karein.",
        "responses": [("Meri family bura maan jayegi.", "Is liye hum plan pehle aur respectfully batayenge. Har dafa unki ناراضی se schedule decide nahi ho sakta."), ("Tum jab chaho apne ghar chali jao.", "Main sirf permission nahi, family time ki shared planning aur transport bhi discuss kar rahi hoon.")],
        "progress": ["Visits are placed on a shared calendar.", "Both families are considered without exact scorekeeping.", "Changes are discussed between partners before being promised to relatives."],
        "related": ["family-boundaries", "supporting-parents-financially", "joint-family-privacy"],
        "urdu": "dono-khandanon-se-mulaqat",
        "image_alt": "Pakistani couple planning visits to both families on a shared calendar",
    },
    "pausing-when-shouting": {
        "title": "How to Pause a Conversation When Someone Is Shouting | DilSe Pakistan",
        "heading": "Pause the discussion when voices rise",
        "description": "Prepare a short boundary and safe next step when a relationship conversation becomes heated.",
        "intro": "A pause is useful only when it reduces escalation and does not trap someone in a threatening situation. Keep the sentence short, stop debating the original issue and state whether you will return at a specific time or seek support first.",
        "situations": ["Voices rise and neither partner can finish a sentence.", "Shouting includes insults, threats, blocking a doorway or breaking objects.", "A pause is treated as permission to follow someone from room to room."],
        "prepare": ["Choose a short phrase you can use without explaining the whole issue.", "Identify a place you can move to safely and a person you can contact.", "Do not promise a private follow-up if you believe returning to the conversation would be unsafe."],
        "gentle": "Hum dono ki awaaz unchi ho rahi hai. Main bees minute ka break lena chahti hoon aur phir nau baje baat continue kar sakte hain.",
        "direct": "Main shouting ke saath yeh conversation continue nahi karungi. Main ab yahan se ja rahi hoon. Mere peeche mat aao.",
        "responses": [("Abhi baat khatam karo.", "Main abhi safely baat nahi kar sakti. Main pause le rahi hoon."), ("Bahar gayi to dekh lena.", "A threat changes this from a communication problem to a safety concern. Move toward safety and contact trusted or emergency support when possible.")],
        "progress": ["A timed pause is respected without pursuit or punishment.", "The discussion resumes only when both people can speak without intimidation.", "Threats, blocked exits or physical aggression lead to a safety response rather than another script."],
        "related": ["disrespectful-conversations", "talking-without-argument", "silent-treatment"],
        "urdu": "cheekhne-par-waqfa",
        "image_alt": "Pakistani woman moving to a safer space after pausing a heated conversation",
    },
}


ADDITIONAL_URDU_TOPICS = {
    "aitemad-phone-raazdari": {"english": "trust-and-privacy", "title": "شادی میں اعتماد اور فون کی رازداری پر بات | دل سے پاکستان", "heading": "اعتماد اور فون کی رازداری پر حقائق کے ساتھ بات کریں", "description": "فون، پاس ورڈ، شک اور ذاتی حدود پر گفتگو کی تیاری کریں۔", "intro": "فون دیکھنے کی نئی درخواست کے کئی مطلب ہو سکتے ہیں۔ پہلے یہ واضح کریں کہ کیا بدلا، پہلے کیا اصول تھا اور کیا ایک ہی اصول دونوں پر لاگو ہوگا۔", "points": ["دیکھے گئے عمل کو بیان کریں، نیت کا اندازہ نہ لگائیں۔", "پہلے سے موجود رازداری کے اصول کو یاد کریں۔", "تسلی اور نگرانی کو الگ رکھ کر منصفانہ اصول مانگیں۔"], "script": "پہلے ہم ایک دوسرے کے فون اس طرح چیک نہیں کرتے تھے۔ میں سمجھنا چاہتی ہوں کہ اب کیا بدلا ہے اور پھر دونوں کے لیے ایک منصفانہ اصول طے کرنا چاہتی ہوں۔"},
    "baghair-jhagray-baat": {"english": "talking-without-argument", "title": "بغیر جھگڑے مشکل بات کیسے شروع کریں | دل سے پاکستان", "heading": "ایک مسئلے پر رہ کر گفتگو شروع کریں", "description": "مشکل بات شروع کرنے، وقفہ لینے اور پرانے جھگڑے نہ کھولنے کی تیاری کریں۔", "intro": "نرم آغاز دوسرے شخص کے ردعمل کو قابو نہیں کر سکتا، لیکن مقصد واضح کر سکتا ہے۔ ایک واقعہ، اس کا اثر اور ایک درخواست منتخب کریں۔", "points": ["ایسا وقت چنیں جب کسی کو فوراً جانا نہ ہو۔", "موضوع کو ایک واقعے اور ایک درخواست تک محدود رکھیں۔", "وقفے کے بعد دوبارہ بات کا وقت پہلے سے سوچیں۔"], "script": "میں لڑنا نہیں چاہتی۔ میں صرف کل والی بات سمجھنا اور آئندہ کے لیے ایک طریقہ طے کرنا چاہتی ہوں۔ کیا ابھی دس منٹ بات ہو سکتی ہے؟"},
    "joint-family-mein-raazdari": {"english": "joint-family-privacy", "title": "جوائنٹ فیملی میں میاں بیوی کی رازداری | دل سے پاکستان", "heading": "مشترکہ گھر میں عملی رازداری مانگیں", "description": "کمرے، نجی وقت، ذاتی معلومات اور مداخلت پر گفتگو کی تیاری کریں۔", "intro": "مشترکہ گھر میں رازداری خاندان سے دوری نہیں۔ واضح کریں کہ ضرورت جگہ، وقت یا معلومات سے متعلق ہے اور ایسا اصول تجویز کریں جس پر سب عمل کر سکیں۔", "points": ["طے کریں کہ ضرورت جگہ، نجی وقت یا معلومات کی ہے۔", "دروازہ کھٹکھٹانے یا مخصوص وقت جیسا واضح اصول رکھیں۔", "طے کریں کہ ہر شریک حیات اپنے رشتہ داروں سے کیسے بات کرے گا۔"], "script": "مجھے ہم دونوں کے لیے روز کچھ نجی وقت چاہیے۔ کیا ہم کھانے کے بعد بیس منٹ اپنے کمرے میں بغیر مداخلت کے رکھ سکتے ہیں؟"},
    "shadi-ke-baad-career": {"english": "career-after-marriage", "title": "شادی کے بعد کام اور کیریئر پر بات | دل سے پاکستان", "heading": "کیریئر کے فیصلے کو عملی منصوبے میں بدلیں", "description": "شادی کے بعد کام، دوبارہ ملازمت اور گھر کی ذمہ داریوں پر گفتگو کی تیاری کریں۔", "intro": "کام کا فیصلہ آمدنی، سفر، بچوں اور گھر کے کام کو بدل سکتا ہے۔ نوکری کی تفصیل اور گھر میں درکار تبدیلیاں لکھ کر بات کریں۔", "points": ["اوقات، آمدنی، سفر اور شروع ہونے کی تاریخ سامنے رکھیں۔", "بچوں اور گھر کے کام کی نئی تقسیم لکھیں۔", "رشتہ داروں کی رائے اور میاں بیوی کے عملی خدشات الگ رکھیں۔"], "script": "میں اس نوکری کو سنجیدگی سے دیکھنا چاہتی ہوں۔ کیا ہم اوقات، سفر اور گھر کی ذمہ داریاں لکھ کر دیکھیں کہ یہ کیسے ممکن ہو سکتی ہے؟"},
    "qurbat-aur-pyar": {"english": "intimacy-and-affection", "title": "شادی میں قربت اور پیار پر بات | دل سے پاکستان", "heading": "قربت، پیار اور رضامندی پر احترام سے بات کریں", "description": "جذباتی اور جسمانی قربت، پیار اور رضامندی پر نجی گفتگو کی تیاری کریں۔", "intro": "قربت پر بات رد کیے جانے یا مایوسی کے فوراً بعد مشکل ہوتی ہے۔ پرسکون وقت چنیں، اپنا تجربہ بیان کریں اور رضامندی، صحت، تھکن اور رازداری کے لیے جگہ رکھیں۔", "points": ["بات قربت کے لمحے سے الگ وقت پر کریں۔", "پیار، جذباتی قربت اور جنسی تعلق کو ایک ہی درخواست نہ بنائیں۔", "دونوں کو انکار، وقت مانگنے یا صحت کا مسئلہ بتانے کی گنجائش دیں۔"], "script": "مجھے تمہارے ساتھ قربت اور پیار کی کمی محسوس ہوتی ہے۔ میں دباؤ نہیں ڈالنا چاہتی۔ کیا ہم سکون سے بات کر سکتے ہیں کہ ہم دونوں کیسا محسوس کر رہے ہیں؟"},
    "bachon-ke-liye-khandani-dabao": {"english": "pressure-about-children", "title": "بچوں کے لیے خاندانی دباؤ پر بات | دل سے پاکستان", "heading": "بچوں کے سوالات کا جواب مل کر طے کریں", "description": "بچوں، وقت، صحت اور نجی معلومات کے بارے میں خاندان کے دباؤ پر گفتگو کریں۔", "intro": "بچوں کے بارے میں سوالات نجی فیصلوں، صحت اور خاندان کی توقعات سے جڑے ہو سکتے ہیں۔ پہلے میاں بیوی طے کریں کہ کیا نجی رہے گا اور بار بار سوال پر کیا جواب دیا جائے گا۔", "points": ["طے کریں کہ کون سی معلومات صرف میاں بیوی اور ڈاکٹر تک محدود ہیں۔", "رشتہ داروں کے لیے ایک مختصر مشترکہ جواب بنائیں۔", "اپنی رائے کو باہر کے دباؤ سے الگ رکھ کر بات کریں۔"], "script": "خاندان کے سوالات سے مجھے دباؤ محسوس ہوتا ہے۔ کیا ہم طے کر سکتے ہیں کہ کیا نجی رہے گا اور اگلی بار ہم دونوں کیا جواب دیں گے؟"},
    "khamoshi-se-saza": {"english": "silent-treatment", "title": "شادی میں خاموشی سے سزا ملے تو کیا کہیں | دل سے پاکستان", "heading": "جب خاموشی گفتگو کی جگہ لے لے", "description": "اختلاف کے بعد طویل خاموشی پر پرسکون اور واضح جواب تیار کریں۔", "intro": "پرسکون ہونے کے لیے وقت مدد دے سکتا ہے، لیکن بغیر وضاحت کی خاموشی دوسرے شخص کو اندازے میں رکھتی ہے۔ وقفے کی مدت اور دوبارہ گفتگو کا وقت واضح مانگیں۔", "points": ["واضح وقفے اور غیر معینہ خاموشی میں فرق کریں۔", "ایک حالیہ واقعہ اور اس کا عملی اثر بیان کریں۔", "دوبارہ بات کے لیے مخصوص وقت مانگیں۔"], "script": "اگر تمہیں وقت چاہیے تو میں جگہ دے سکتی ہوں۔ بس بتا دو کہ ہم اس بات پر کب واپس آئیں گے تاکہ میں اندازہ نہ لگاتی رہوں۔"},
    "joint-family-se-alag": {"english": "separate-from-joint-family", "title": "جوائنٹ فیملی سے الگ رہنے پر بات | دل سے پاکستان", "heading": "خاندان کی توہین کیے بغیر الگ گھر پر بات کریں", "description": "الگ گھر، خرچ، والدین کی مدد اور رازداری پر عملی گفتگو کی تیاری کریں۔", "intro": "الگ گھر کی درخواست کو خاندان سے انکار سمجھا جا سکتا ہے۔ روزمرہ ضرورت، بجٹ، والدین کی دیکھ بھال اور خاندان سے تعلق کو الگ الگ واضح کریں۔", "points": ["انفرادی رشتہ داروں پر حملہ کیے بغیر روزمرہ مسائل لکھیں۔", "کرایہ، جگہ اور والدین کی مدد کا حقیقی منصوبہ بنائیں۔", "آزمائشی مدت یا دوبارہ جائزے کی تاریخ تجویز کریں۔"], "script": "میں خاندان سے تعلق کم نہیں کرنا چاہتی۔ میں چاہتی ہوں کہ ہم الگ گھر کے خرچ اور منصوبے کو دیکھیں تاکہ رازداری اور خاندان کی مدد دونوں چل سکیں۔"},
    "zaati-baat-family-se-share": {"english": "sharing-private-matters", "title": "شوہر ذاتی بات خاندان سے شیئر کرے تو کیا کہیں | دل سے پاکستان", "heading": "ذاتی بات شیئر کرنے سے پہلے اجازت مانگیں", "description": "ازدواجی اختلاف، صحت اور مالی معلومات کو نجی رکھنے پر گفتگو کریں۔", "intro": "خاندان سے مدد لینا مناسب ہو سکتا ہے، مگر شریک حیات کی ذاتی معلومات اجازت کے بغیر شیئر ہونے سے اعتماد متاثر ہوتا ہے۔ واضح کریں کہ کن باتوں کے لیے پہلے رضامندی ضروری ہے۔", "points": ["وہ خاص معلومات بتائیں جو شیئر ہوئی۔", "مدد لینے اور غیر ضروری تفصیل بتانے میں فرق کریں۔", "نجی، قابل شیئر اور اجازت والی معلومات کی حد طے کریں۔"], "script": "میں سمجھتی ہوں کہ کبھی خاندان سے مدد چاہیے ہوتی ہے۔ میری ذاتی بات شیئر کرنے سے پہلے میں چاہتی ہوں کہ تم مجھ سے پوچھو۔"},
    "walidain-ki-mali-madad": {"english": "supporting-parents-financially", "title": "شادی کے بعد والدین کی مالی مدد پر بات | دل سے پاکستان", "heading": "گھر کے خرچ کے ساتھ والدین کی مدد طے کریں", "description": "والدین کی باقاعدہ مدد، ہنگامی ضرورت اور مشترکہ بجٹ پر گفتگو کریں۔", "intro": "والدین کی مدد ذمہ داری اور محبت کا اظہار ہو سکتی ہے۔ رقم یا وقت چھپانے سے مسئلہ بڑھتا ہے۔ گھر کے لازمی خرچ کے ساتھ باقاعدہ اور اضافی مدد کا اصول بنائیں۔", "points": ["آمدنی، بل، قرض، بچت اور موجودہ مدد لکھیں۔", "باقاعدہ مدد اور ہنگامی ضرورت الگ کریں۔", "اضافی رقم کے لیے مشترکہ فیصلے کی حد طے کریں۔"], "script": "میں دونوں طرف کے والدین کی ضرورت کا احترام کرتی ہوں۔ کیا ہم بلوں کے بعد باقاعدہ مدد اور ہنگامی رقم کا اصول مل کر طے کر سکتے ہیں؟"},
    "bachon-ki-taleem": {"english": "children-education", "title": "بچوں کی تعلیم پر میاں بیوی کیسے بات کریں | دل سے پاکستان", "heading": "تعلیم کا فیصلہ ایک ہی معلومات سے کریں", "description": "اسکول، فیس، ٹیوشن، زبان اور بچے کی ضرورت پر گفتگو کی تیاری کریں۔", "intro": "تعلیم کے فیصلے میں خرچ، اقدار، سفر اور بچے کی ضرورت شامل ہیں۔ ایک ہی معلومات اور متفقہ معیار سے آپشنز کا موازنہ کریں۔", "points": ["فیس، فاصلہ، کلاس اور داخلے کی معلومات جمع کریں۔", "دونوں والدین کی امید اور تشویش الگ الگ سنیں۔", "بچے کی ضرورت شامل کریں مگر اسے والدین میں سے ایک چننے پر مجبور نہ کریں۔"], "script": "ہم دونوں بچے کے لیے اچھا چاہتے ہیں۔ کیا ہم اسکولوں کو فیس، فاصلے اور اس کی سیکھنے کی ضرورت کے مطابق دیکھ سکتے ہیں؟"},
    "shehar-ya-mulk-tabdeeli": {"english": "moving-city-or-abroad", "title": "دوسرے شہر یا ملک منتقل ہونے پر بات | دل سے پاکستان", "heading": "منتقلی کے فیصلے کو واضح معلومات میں بدلیں", "description": "نوکری، امیگریشن، والدین، بچوں اور دونوں کیریئر پر گفتگو کریں۔", "intro": "منتقلی آمدنی کے ساتھ دونوں کیریئر، بچوں اور والدین کی دیکھ بھال کو بدل سکتی ہے۔ پکی معلومات، اندازے اور ہر شریک حیات کی قیمت الگ لکھیں۔", "points": ["تنخواہ، ویزا، گھر اور وقت کی پکی اور غیر پکی معلومات الگ کریں۔", "دونوں کیریئر اور نگہداشت کی ذمہ داریاں شامل کریں۔", "حتمی جواب سے پہلے درکار معلومات اور تاریخ طے کریں۔"], "script": "یہ منتقلی ہم دونوں کی زندگی بدلے گی۔ کیا ہم آمدنی کے ساتھ میری نوکری، بچوں اور والدین کی دیکھ بھال بھی ایک منصوبے میں لکھ سکتے ہیں؟"},
    "social-media-hudood": {"english": "social-media-boundaries", "title": "شادی میں واٹس ایپ اور سوشل میڈیا کی حدود | دل سے پاکستان", "heading": "آن لائن کیا نجی رہے گا، مل کر طے کریں", "description": "تصاویر، پیغامات، آن لائن دوستی اور فیملی گروپس پر گفتگو کریں۔", "intro": "تصویر، پیغام یا ذاتی خبر شیئر کرنے کے بارے میں میاں بیوی کی رائے مختلف ہو سکتی ہے۔ ہر اکاؤنٹ تک رسائی کے بجائے اجازت والے عمل واضح کریں۔", "points": ["خاص پوسٹ، پیغام یا رابطہ بیان کریں۔", "عوامی پوسٹ، نجی پیغام اور پاس ورڈ الگ موضوع رکھیں۔", "ایک ہی اجازت کا اصول دونوں پر رکھیں۔"], "script": "میری تصویر یا ذاتی خبر پوسٹ کرنے سے پہلے میں چاہتی ہوں کہ ہم ایک دوسرے سے پوچھیں۔ کیا یہ اصول ہم دونوں کے لیے ہو سکتا ہے؟"},
    "baat-chhupane-ke-baad-bharosa": {"english": "rebuilding-trust-after-secrecy", "title": "بات چھپانے کے بعد اعتماد کیسے بحال کریں | دل سے پاکستان", "heading": "جھوٹ یا رازداری کے بعد عملی مرمت مانگیں", "description": "چھپے ہوئے خرچ، پیغام یا منصوبے کے بعد اعتماد پر گفتگو کی تیاری کریں۔", "intro": "اعتماد فوری یقین یا مستقل نگرانی سے واپس نہیں آتا۔ کیا ہوا، اس کا اثر اور اسی واقعے سے متعلق محدود عملی قدم واضح ہونا چاہیے۔", "points": ["جو معلوم ہے اور جس کا جواب چاہیے الگ کریں۔", "اسی خلاف ورزی سے متعلق مرمت کا قدم مانگیں۔", "مکمل معلومات سے پہلے معافی یا مستقبل کا وعدہ نہ کریں۔"], "script": "جو بات چھپائی گئی اس سے میرا اعتماد متاثر ہوا ہے۔ میں پہلے پوری بات سمجھنا اور پھر عملی قدم طے کرنا چاہتی ہوں۔"},
    "be-izzati-wali-guftagu": {"english": "disrespectful-conversations", "title": "گفتگو میں بے عزتی ہو تو کیا کہیں | دل سے پاکستان", "heading": "اختلاف میں بے عزتی کی حد واضح کریں", "description": "طعنے، مذاق، گالی یا بار بار بات کاٹنے پر واضح جملہ تیار کریں۔", "intro": "اختلاف توہین یا دھمکی کے بغیر جاری رہ سکتا ہے۔ ناقابل قبول عمل واضح کریں اور ضرورت پر گفتگو روک کر واپس آنے کی شرط بتائیں۔", "points": ["خاص لفظ یا عمل منتخب کریں۔", "ایک مختصر حد والا جملہ تیار کریں۔", "بات بڑھنے پر محفوظ جگہ اور مدد کا راستہ سوچیں۔"], "script": "میں اس مسئلے پر بات کرنا چاہتی ہوں لیکن بے عزتی کے ساتھ نہیں۔ اگر ہم معمول کے لہجے میں بات کر سکیں تو میں جاری رکھوں گی۔"},
    "jazbati-support-mangna": {"english": "asking-for-emotional-support", "title": "شوہر سے جذباتی مدد کیسے مانگیں | دل سے پاکستان", "heading": "مشورے سے پہلے سنے جانے کی درخواست کریں", "description": "سننے، تسلی، مشورے یا عملی مدد کی واضح درخواست تیار کریں۔", "intro": "کبھی شریک حیات حل پیش کرتا ہے جبکہ آپ کو سننے یا تسلی کی ضرورت ہوتی ہے۔ مسئلہ بیان کرنے سے پہلے بتائیں کہ اس وقت کس قسم کا جواب مدد دے گا۔", "points": ["طے کریں کہ سننا، تسلی، مشورہ یا عملی مدد چاہیے۔", "بغیر مداخلت کے مناسب وقت کی درخواست کریں۔", "واضح کریں کہ بعد میں مشورہ چاہیے یا نہیں۔"], "script": "مجھے ابھی حل سے پہلے دس منٹ صرف سنے جانے کی ضرورت ہے۔ کیا تم میری بات مکمل ہونے تک سن سکتے ہو؟"},
    "dono-khandanon-se-mulaqat": {"english": "visiting-families-fairly", "title": "شادی کے بعد دونوں خاندانوں سے ملاقات | دل سے پاکستان", "heading": "خاندانی ملاقات کو وفاداری کا مقابلہ نہ بنائیں", "description": "عید، ہفتہ وار ملاقات، سفر اور دونوں خاندانوں کی توقعات پر بات کریں۔", "intro": "عید، شادی یا بیماری پر ملاقات احترام سے جڑی محسوس ہو سکتی ہے۔ کیلنڈر، سفر اور موجودہ ضرورت دیکھ کر منصوبہ بنائیں، یہ ثابت کرنے کی کوشش نہ کریں کہ کون سا خاندان زیادہ اہم ہے۔", "points": ["اگلے مہینے کی تاریخیں اور سفر لکھیں۔", "لازمی موقع اور بدل سکنے والی ملاقات الگ کریں۔", "رشتہ داروں کو منصوبہ بتانے کا مشترکہ طریقہ طے کریں۔"], "script": "دونوں خاندان ہمارے لیے اہم ہیں۔ کیا ہم اگلے مہینے کا کیلنڈر دیکھ کر ملاقاتیں پہلے طے کر سکتے ہیں؟"},
    "cheekhne-par-waqfa": {"english": "pausing-when-shouting", "title": "چیخنے پر گفتگو کیسے روکیں | دل سے پاکستان", "heading": "آواز بلند ہونے پر بات روکیں", "description": "گرم گفتگو میں مختصر حد، وقفہ اور محفوظ اگلا قدم تیار کریں۔", "intro": "وقفہ تب مدد دیتا ہے جب کشیدگی کم ہو اور کسی کو خطرے میں نہ رکھے۔ مختصر جملہ کہیں، اصل بحث روکیں اور محفوظ ہو تو واپس آنے کا وقت بتائیں۔", "points": ["وضاحت کے بغیر استعمال ہونے والا مختصر جملہ چنیں۔", "محفوظ جگہ اور رابطے کے شخص کا سوچیں۔", "خطرہ ہو تو اکیلے دوبارہ بات کا وعدہ نہ کریں۔"], "script": "میں چیخنے کے ساتھ یہ گفتگو جاری نہیں رکھوں گی۔ میں اب وقفہ لے رہی ہوں۔ محفوظ اور پرسکون ہونے پر بات ہوگی۔"},
}
