"""Source copy for DilSe's public conversation guides."""

TOPICS = {
    "family-boundaries": {
        "title": "How to Talk About Family Boundaries in Marriage | DilSe Pakistan",
        "heading": "Talking about family boundaries without dismissing family",
        "description": "Prepare a respectful conversation about privacy, in-laws and family expectations in a Pakistani marriage.",
        "intro": "A boundary conversation can recognise the value of family while still asking for privacy, fairness or a decision the couple makes together. The aim is to address one recurring situation without turning the discussion into a judgment about the whole family.",
        "situations": ["A private disagreement is discussed with relatives before both partners agree to share it.", "A family commitment is accepted on behalf of the couple without checking first.", "One partner feels expected to stay silent so that nobody outside the marriage feels upset."],
        "prepare": ["Write down the exact event you want to discuss, including what was said or decided.", "Separate the relative's behaviour from your partner's response. Your request should focus on what your partner can do.", "Choose one boundary you can both follow, such as checking with each other before answering a family request."],
        "gentle": "Main aap ke ghar walon ki izzat karti hoon. Saath hi, main chahti hoon ke hamare kuch faislay pehle hum dono aapas mein karein. Kya hum jawab dene se pehle ek doosre se baat kar sakte hain?",
        "direct": "Kal jab hamara faisla mujh se poochay baghair family ko bata diya gaya, mujhe laga ke meri rai shamil nahi thi. Agli baar main chahti hoon ke hum pehle aapas mein agree karein.",
        "responses": [("Tum meri family ko pasand nahi karti.", "Main family ko reject nahi kar rahi. Main us ek faislay ki baat kar rahi hoon jo hum dono se related tha."), ("Ghar mein aise hi hota hai.", "Main samajhti hoon ke yeh purana tareeqa hai. Main pooch rahi hoon ke hum apni marriage mein kis tareeqay par agree karna chahte hain.")],
        "progress": ["Both partners can state the boundary in the same words.", "The couple knows who will respond when the issue comes up again.", "A mistake can be acknowledged without reopening every past family conflict."],
        "related": ["joint-family-privacy", "talking-without-argument", "trust-and-privacy"],
        "urdu": "khandani-hudood",
        "image_alt": "Pakistani couple discussing family boundaries in a quiet room while relatives sit in the background",
    },
    "household-responsibilities": {
        "title": "How to Discuss Household Responsibilities | DilSe Pakistan",
        "heading": "Ask for ownership, not occasional help",
        "description": "Prepare a conversation about household work, childcare and mental load with your husband or partner.",
        "intro": "Household work includes noticing, planning and following up, not only completing the visible task. A useful request transfers responsibility for a defined area from start to finish, so one partner does not remain the manager of every task.",
        "situations": ["One partner completes tasks only after being reminded several times.", "Childcare or school work is treated as one person's default responsibility.", "Both partners work, but planning meals, appointments and family obligations still falls mainly to one person."],
        "prepare": ["List the recurring tasks for one week, including planning and reminders.", "Choose one complete area to transfer instead of arguing about who works harder overall.", "Agree on the required result and deadline, while leaving room for the person responsible to choose the method."],
        "gentle": "Main chahti hoon ke hum ghar ke kaam ko dobara dekhein. Kya tum bachon ki school administration, notices, forms, fees aur follow-up, poori tarah handle kar sakte ho?",
        "direct": "Mujhe reminders dene aur phir kaam check karne se bhi woh zimmedari meri hi rehti hai. Main chahti hoon ke school administration ki ownership ab tum lo.",
        "responses": [("Bas bata diya karo, main kar dunga.", "Batana aur yaad dilana bhi planning ka hissa hai. Main chahti hoon ke yeh poora area tum track karo."), ("Tumhein mera tareeqa pasand nahi aayega.", "Hum result aur deadline par agree kar sakte hain. Har step mera tareeqa hona zaroori nahi.")],
        "progress": ["Each recurring task has one named owner.", "The owner notices deadlines without waiting for a reminder.", "The arrangement is reviewed after two weeks using examples rather than accusations."],
        "related": ["career-after-marriage", "money-conversations", "talking-without-argument"],
        "urdu": "ghar-ki-zimmedariyan",
        "image_alt": "Pakistani couple planning household responsibilities with a calendar and shopping notes",
    },
    "money-conversations": {
        "title": "How to Talk About Money in Marriage | DilSe Pakistan",
        "heading": "Prepare a clear conversation about money",
        "description": "Plan a conversation about household expenses, family support, savings or career decisions in a Pakistani marriage.",
        "intro": "Money discussions become harder when household needs, support for parents and future plans compete for the same income. Start with the figures, identify the decision that must be made and avoid treating a different priority as proof that one partner does not care.",
        "situations": ["School fees or bills are late while money is being committed elsewhere.", "Financial help for parents or siblings is not discussed before it is sent.", "One partner does not know the household income, debt or monthly commitments."],
        "prepare": ["Bring the current figures: income, fixed bills, debt payments, savings and family support.", "Decide which single question needs an answer in this conversation.", "Set a private time to talk, rather than raising the issue during a purchase or in front of relatives."],
        "gentle": "Main samajhti hoon ke Ammi Abbu ki support important hai. Saath hi bachon ki fees late ho rahi hai. Kya hum fixed expenses rakh kar, phir support ka amount mil kar decide kar sakte hain?",
        "direct": "Is mahine fees ki tareekh nikal gayi aur mujhe transfer ke baad pata chala. Main chahti hoon ke family support ka amount bhejne se pehle hum dono budget dekhein.",
        "responses": [("Mere paisay hain, mujhe poochne ki zaroorat nahi.", "Main har kharch ki permission nahi maang rahi. Main un commitments par joint decision chahti hoon jo household bills ko affect karte hain."), ("Tum mere parents ki help rokna chahti ho.", "Main support band karne ki baat nahi kar rahi. Main amount aur timing aise decide karna chahti hoon ke dono zimmedariyan poori hon.")],
        "progress": ["Both partners can see the same monthly figures.", "Family support has an agreed amount or a review rule.", "Large unplanned expenses have a threshold that requires a discussion."],
        "related": ["career-after-marriage", "household-responsibilities", "family-boundaries"],
        "urdu": "paise-ki-baat",
        "image_alt": "Pakistani couple reviewing household finances with a calculator and notebook",
    },
    "trust-and-privacy": {
        "title": "How to Discuss Trust and Phone Privacy | DilSe Pakistan",
        "heading": "Discuss trust and privacy using the facts",
        "description": "Think through a change in phone privacy, jealousy or trust before deciding what it means or what to say.",
        "intro": "A new request to see a phone can have different meanings in different relationships. Start with what changed, what the previous agreement was and whether the expectation applies to both partners. Privacy and secrecy are not automatically the same thing.",
        "situations": ["A partner begins asking for passwords after years of a different agreement.", "Messages are checked without permission, or one partner is expected to prove where they are.", "A past breach of trust is repeatedly used to justify unlimited monitoring."],
        "prepare": ["Describe the behaviour you observed without assigning a motive you cannot confirm.", "Recall the privacy agreement you had before, even if it was never stated formally.", "Decide what reassurance you can offer and what access or monitoring you are not comfortable accepting."],
        "gentle": "Pehle hum phones ko is tarah check nahi karte thay. Main samajhna chahti hoon ke ab kya badla hai, phir hum dono ke liye ek fair agreement banana chahti hoon.",
        "direct": "Kal mera phone meri permission ke baghair check hua. Main is par comfortable nahi hoon. Agar koi concern hai to main us par baat karungi, lekin secret checking accept nahi karungi.",
        "responses": [("Agar kuch chhupana nahi to problem kya hai?", "Privacy ki zaroorat chhupane ka saboot nahi. Main concern sunne ko tayyar hoon, lekin rule dono ke liye fair hona chahiye."), ("Tum mujh par trust nahi karti.", "Main trust par hi baat kar rahi hoon. Monitoring ke bajaye main chahti hoon ke hum concern aur reassurance clearly decide karein.")],
        "progress": ["Both partners know what is private and what should be shared.", "The same rule applies to each partner.", "A trust concern can be raised directly without secret checks or repeated interrogation."],
        "related": ["joint-family-privacy", "family-boundaries", "emotional-connection"],
        "image_alt": "Pakistani couple discussing phone privacy with a phone placed face down between them",
    },
    "emotional-connection": {
        "title": "How to Talk About Emotional Distance | DilSe Pakistan",
        "heading": "Put emotional distance into words",
        "description": "Prepare a conversation about affection, closeness and emotional distance with your husband or partner.",
        "intro": "Saying that the relationship no longer feels close can be too broad for either partner to answer. Describe what has changed in ordinary life, what you miss and one small action that would help you feel connected again.",
        "situations": ["Most conversations are now about bills, children or household tasks.", "Attempts to share a worry receive a quick solution, a joke or no response.", "Affection has reduced and neither partner has named the change."],
        "prepare": ["Choose a recent example of feeling distant rather than judging the whole relationship.", "Name the kind of connection you miss, such as attention, affection or time alone.", "Ask for one repeatable action that is realistic within your current routine."],
        "gentle": "Mujhe lagta hai hum dono sirf routine manage kar rahe hain. Main miss karti hoon ke hum araam se baith kar baat karein. Kya hum is hafte aadha ghanta sirf ek doosre ke liye rakh sakte hain?",
        "direct": "Pichlay kuch hafton se jab main baat shuru karti hoon to hum phone ya kaam mein lag jaate hain. Main chahti hoon ke hum haftay mein ek dafa bina phone ke saath baithain.",
        "responses": [("Main itni mehnat kis ke liye karta hoon?", "Main tumhari mehnat ko reject nahi kar rahi. Main keh rahi hoon ke mujhe tumhara waqt aur tawajjo bhi chahiye."), ("Sab theek to hai, phir masla kya hai?", "Routine chal raha hai, lekin main emotionally door mehsoos kar rahi hoon. Main ek chhoti aadat saath try karna chahti hoon.")],
        "progress": ["The request names a behaviour, not a personality flaw.", "Both partners choose a small routine they can repeat.", "They review whether it helped instead of expecting one conversation to fix the distance."],
        "related": ["intimacy-and-affection", "talking-without-argument", "trust-and-privacy"],
        "urdu": "rishtay-mein-doori",
        "image_alt": "Pakistani couple reconnecting over tea during a quiet evening conversation",
    },
    "talking-without-argument": {
        "title": "How to Talk Without Starting an Argument | DilSe Pakistan",
        "heading": "Start a difficult conversation without reopening every fight",
        "description": "Prepare a calm opening, stay with one issue and pause a difficult relationship conversation before it becomes an argument.",
        "intro": "A careful opening cannot control another person's reaction, but it can make your purpose clear. Pick one issue, describe what happened and say what decision or change you want from this conversation.",
        "situations": ["A small request quickly turns into a list of old complaints.", "One partner raises a concern while the other is tired, leaving or already angry.", "Both people interrupt because each expects to be blamed."],
        "prepare": ["Choose a time when neither person has to leave in the next few minutes.", "Reduce the topic to one event and one request.", "Plan a pause sentence in advance so stopping does not sound like abandoning the issue."],
        "gentle": "Main larna nahi chahti. Main sirf kal wali baat samajhna aur aglay dafa ke liye ek tareeqa decide karna chahti hoon. Kya ab das minute baat ho sakti hai?",
        "direct": "Hum ab purani baaton par ja rahe hain. Main aaj sirf kal ke faislay par rehna chahti hoon. Agar ab mushkil hai to hum raat nau baje dobara baat karte hain.",
        "responses": [("Tum hamesha ghalat waqt par shuru karti ho.", "Theek hai, abhi waqt decide kar lete hain. Mujhe is baat ko aaj ya kal address karna hai."), ("Phir se wohi drama.", "Main label par argue nahi karungi. Mere paas ek specific event aur ek request hai, aur main chahti hoon ke hum usay sun lein.")],
        "progress": ["The conversation stays with one event.", "Either partner can request a timed pause without ending the issue.", "The next step is stated before the conversation closes."],
        "related": ["emotional-connection", "family-boundaries", "household-responsibilities"],
        "image_alt": "Pakistani couple listening calmly to each other at a dining table",
    },
    "joint-family-privacy": {
        "title": "Privacy in a Joint Family Home | DilSe Pakistan",
        "heading": "Ask for privacy in a joint family home",
        "description": "Plan a practical conversation about couple privacy, rooms, information and interruptions in a Pakistani joint family home.",
        "intro": "Privacy in a shared home is often a practical arrangement, not a rejection of the family. A useful conversation identifies which space, time or information needs protection and how both partners will explain the agreement to relatives.",
        "situations": ["People enter the couple's room without knocking.", "Personal disagreements or health information are shared with relatives.", "The couple has no reliable time to talk without interruptions."],
        "prepare": ["Decide whether the need concerns physical space, information or private time.", "Ask for a rule that every person can follow, such as knocking and waiting for an answer.", "Agree which partner will explain the rule to their own relatives."],
        "gentle": "Joint family mein sab ki needs hoti hain. Mujhe hum dono ke liye bhi thora private time chahiye. Kya hum dinner ke baad bees minute apne room mein bina interruption rakh sakte hain?",
        "direct": "Aaj hamari personal baat lounge mein share hui. Main chahti hoon ke hamare disagreements kisi aur ko batane se pehle hum dono agree karein.",
        "responses": [("Yeh ghar sab ka hai.", "Bilkul, aur main kisi ko rok nahi rahi. Main sirf knock karke jawab ka wait karne ki request kar rahi hoon."), ("Log kya sochenge?", "Hum isay family se doori nahi, routine aur rest ki zaroorat ke taur par explain kar sakte hain.")],
        "progress": ["The rule is specific enough for relatives to understand.", "Both partners support it consistently.", "Exceptions, such as illness or an urgent matter, are clear."],
        "related": ["family-boundaries", "trust-and-privacy", "intimacy-and-affection"],
        "image_alt": "Pakistani couple speaking privately near their room while family members gather farther away",
    },
    "career-after-marriage": {
        "title": "How to Discuss Career After Marriage | DilSe Pakistan",
        "heading": "Discuss work and career after marriage with a practical plan",
        "description": "Prepare a conversation about working after marriage, returning to work or balancing a career with family responsibilities in Pakistan.",
        "intro": "A career decision can affect income, travel, childcare, household work and family expectations. Discuss those effects directly. Avoid reducing the issue to whether one partner is supportive or traditional.",
        "situations": ["A return to work after a break requires new childcare or transport arrangements.", "A job offer includes hours or travel the couple has not handled before.", "Relatives expect one partner to give up work without a private decision by the couple."],
        "prepare": ["Bring the job details, hours, travel, income and likely start date.", "List the household arrangements that would need to change.", "Separate the couple's practical concerns from relatives' opinions, then decide how the couple will respond to family questions."],
        "gentle": "Main is job ko seriously consider karna chahti hoon. Kya hum hours, transport aur ghar ki zimmedariyan likh kar dekhein ke isay workable kaise banaya ja sakta hai?",
        "direct": "Main career ka faisla sirf family pressure ki wajah se close nahi karna chahti. Agar tumhein practical concern hai to main us par plan banana chahti hoon.",
        "responses": [("Ghar kaun sambhalega?", "Yeh valid practical question hai. Chalo current tasks likh kar decide karte hain ke kaun sa task kis ke paas hoga aur paid help ki zaroorat hai ya nahi."), ("Meri family agree nahi karegi.", "Unki rai sun sakte hain, lekin is decision ka daily effect hum dono par hai. Main chahti hoon ke pehle hum apna decision banayein.")],
        "progress": ["The plan covers time, transport, childcare and household ownership.", "A trial period has a review date.", "Both partners use one agreed response when relatives ask about the decision."],
        "related": ["household-responsibilities", "money-conversations", "family-boundaries"],
        "image_alt": "Pakistani woman discussing her career plans with her husband beside a laptop and calendar",
    },
    "intimacy-and-affection": {
        "title": "How to Talk About Intimacy and Affection | DilSe Pakistan",
        "heading": "Talk about affection and intimacy with respect",
        "description": "Prepare a private, respectful conversation about affection, physical closeness and consent in a marriage.",
        "intro": "Affection and physical intimacy can be difficult to discuss, especially when the only conversations happen after rejection or disappointment. Choose a neutral moment, speak about your own experience and leave room for consent, health, stress and privacy concerns.",
        "situations": ["Everyday affection has reduced and both partners avoid naming it.", "One partner feels pressured while the other feels repeatedly rejected.", "Privacy, exhaustion, health or conflict is affecting physical closeness."],
        "prepare": ["Have the conversation outside an intimate moment, when either person can answer without immediate pressure.", "Distinguish affection, emotional closeness and sex instead of treating them as one request.", "Use language that allows either partner to say no, ask for time or raise a health concern."],
        "gentle": "Main tumhare saath closeness miss kar rahi hoon, sirf physical nahi balkay affection bhi. Main pressure nahi dena chahti. Kya hum araam se baat kar sakte hain ke hum dono kaisa mehsoos kar rahe hain?",
        "direct": "Jab mana karne par narazgi hoti hai to mujhe pressure mehsoos hota hai. Main chahti hoon ke consent ko respect kiya jaye aur hum closeness ke bare mein alag waqt par baat karein.",
        "responses": [("Tumhein ab meri parwah nahi.", "Meri boundary parwah ki kami nahi. Main chahti hoon ke closeness dono ki marzi aur comfort ke saath ho."), ("Is par baat karna ajeeb hai.", "Mujhe bhi awkward lagta hai, lekin assumptions se doori barh rahi hai. Hum sirf das minute se shuru kar sakte hain.")],
        "progress": ["Both partners can describe comfort and consent without punishment or ridicule.", "Affection is discussed separately from obligation.", "Health concerns are taken to an appropriate qualified clinician when needed."],
        "related": ["emotional-connection", "joint-family-privacy", "talking-without-argument"],
        "image_alt": "Married Pakistani couple sharing a quiet and affectionate moment in a private living room",
    },
    "pressure-about-children": {
        "title": "How to Discuss Family Pressure About Children | DilSe Pakistan",
        "heading": "Respond together to pressure about having children",
        "description": "Prepare a conversation with your spouse about family pressure, timing, fertility questions and privacy around having children.",
        "intro": "Questions about children can involve private decisions, health information, grief and family expectations. The first conversation is often between partners: what is private, what response to give and who will speak when relatives ask again.",
        "situations": ["Relatives repeatedly ask when the couple will have a child.", "One partner shares fertility or health information without the other's agreement.", "The couple has different views about timing but family pressure is forcing the discussion."],
        "prepare": ["Decide which information belongs only to the couple and medical professionals.", "Agree on one short response for relatives that does not invite further questions.", "Discuss your own views separately from the pressure coming from outside the marriage."],
        "gentle": "Family ke sawalon se mujhe pressure mehsoos hota hai. Kya hum decide kar sakte hain ke kya private rahega aur agli baar hum dono kya jawab denge?",
        "direct": "Meri health ki information meri permission ke baghair share hui. Main chahti hoon ke ab se is topic par koi detail batane se pehle hum dono agree karein.",
        "responses": [("Woh sirf fikr kar rahe hain.", "Main unki niyyat par baat nahi kar rahi. Sawalon ka effect mujh par pressure ki tarah ho raha hai, is liye humein ek boundary chahiye."), ("Kuch jawab na dein to log aur poochein ge.", "Hum ek hi short jawab repeat kar sakte hain: jab koi khabar hogi hum khud bata denge." )],
        "progress": ["Both partners use the same response with relatives.", "Private health details are shared only with consent.", "The couple can discuss timing without using family pressure as an argument."],
        "related": ["family-boundaries", "joint-family-privacy", "trust-and-privacy"],
        "image_alt": "Pakistani couple supporting each other during a private talk while relatives gather in another room",
    },
}


URDU_TOPICS = {
    "khandani-hudood": {
        "english": "family-boundaries",
        "title": "شادی میں خاندانی حدود پر بات کیسے کریں | دل سے پاکستان",
        "heading": "خاندان کی عزت کے ساتھ اپنی حدود کی بات کریں",
        "description": "پاکستانی شادی میں سسرال، ذاتی فیصلوں اور رازداری کے بارے میں گفتگو کی تیاری کریں۔",
        "intro": "خاندان کی قدر کرنا اور اپنی شادی کے لیے واضح حدود رکھنا ایک دوسرے کی مخالفت نہیں۔ بہتر گفتگو کسی ایک واقعے، اس کے اثر اور آئندہ کے لیے ایک واضح درخواست پر رہتی ہے۔",
        "points": ["جس واقعے پر بات کرنی ہے اسے واضح کریں، پورے خاندان پر فیصلہ نہ دیں۔", "یہ بتائیں کہ شریک حیات کے کس عمل سے فرق پڑ سکتا ہے۔", "ایک ایسا اصول تجویز کریں جس پر دونوں عمل کر سکیں، مثلاً جواب دینے سے پہلے آپس میں بات کرنا۔"],
        "script": "میں آپ کے گھر والوں کی عزت کرتی ہوں۔ ساتھ ہی میں چاہتی ہوں کہ ہمارے کچھ فیصلے پہلے ہم دونوں آپس میں کریں۔ کیا ہم جواب دینے سے پہلے ایک دوسرے سے بات کر سکتے ہیں؟",
    },
    "ghar-ki-zimmedariyan": {
        "english": "household-responsibilities",
        "title": "گھر کی ذمہ داریاں کیسے تقسیم کریں | دل سے پاکستان",
        "heading": "صرف مدد نہیں، مکمل ذمہ داری کی بات کریں",
        "description": "گھر کے کام، بچوں اور ذہنی بوجھ کی منصفانہ تقسیم پر گفتگو کی تیاری کریں۔",
        "intro": "گھر کا کام صرف نظر آنے والا کام مکمل کرنا نہیں۔ کام یاد رکھنا، وقت طے کرنا اور بعد میں دیکھنا بھی ذمہ داری کا حصہ ہے۔ ایک وقت میں ایک مکمل شعبہ طے کریں۔",
        "points": ["ایک ہفتے کے کام لکھیں، جن میں یاد دہانی اور منصوبہ بندی بھی شامل ہو۔", "ایک مکمل شعبہ منتخب کریں، مثلاً اسکول کے فارم، فیس اور رابطہ۔", "نتیجہ اور آخری تاریخ طے کریں، لیکن ہر قدم کی نگرانی اپنے پاس نہ رکھیں۔"],
        "script": "میں چاہتی ہوں کہ تم بچوں کے اسکول کی پوری ذمہ داری لو، نوٹس، فارم، فیس اور فالو اپ، بغیر میری یاد دہانی کے۔",
    },
    "paise-ki-baat": {
        "english": "money-conversations",
        "title": "شادی میں پیسوں پر بات کیسے کریں | دل سے پاکستان",
        "heading": "پیسوں کی گفتگو اعداد اور ایک فیصلے سے شروع کریں",
        "description": "گھر کے خرچ، والدین کی مدد، بچت اور قرض کے بارے میں واضح گفتگو کی تیاری کریں۔",
        "intro": "گھر کے بل، والدین کی مدد اور مستقبل کی بچت ایک ہی آمدنی سے پوری ہو سکتی ہیں۔ گفتگو سے پہلے موجودہ اعداد لکھیں اور طے کریں کہ آج کس ایک فیصلے کی ضرورت ہے۔",
        "points": ["آمدنی، مقررہ بل، قرض، بچت اور خاندانی مدد کی موجودہ رقم لکھیں۔", "مختلف ترجیح کو بے حسی یا خود غرضی کا ثبوت نہ بنائیں۔", "رقم، تاریخ یا دوبارہ جائزے کا وقت طے کریں۔"],
        "script": "میں سمجھتی ہوں کہ امی ابو کی مدد ضروری ہے۔ ساتھ ہی بچوں کی فیس دیر سے جا رہی ہے۔ کیا ہم پہلے مقررہ خرچ رکھ کر پھر مدد کی رقم مل کر طے کر سکتے ہیں؟",
    },
    "rishtay-mein-doori": {
        "english": "emotional-connection",
        "title": "رشتے میں جذباتی دوری پر بات کیسے کریں | دل سے پاکستان",
        "heading": "جذباتی دوری کو روزمرہ مثال سے بیان کریں",
        "description": "شریک حیات کے ساتھ توجہ، قربت اور جذباتی دوری پر گفتگو کی تیاری کریں۔",
        "intro": "یہ کہنا کہ ہم اب قریب نہیں رہے بہت وسیع بات ہے۔ حالیہ مثال سے بتائیں کہ کیا بدلا ہے، آپ کو کس چیز کی کمی محسوس ہوتی ہے اور کون سا چھوٹا عمل مدد دے سکتا ہے۔",
        "points": ["پورے رشتے پر فیصلہ دینے کے بجائے حالیہ واقعہ بیان کریں۔", "واضح کریں کہ آپ وقت، توجہ، بات چیت یا پیار میں سے کیا چاہتی ہیں۔", "ایک چھوٹی اور بار بار کی جا سکنے والی درخواست کریں۔"],
        "script": "مجھے لگتا ہے ہم دونوں صرف روزمرہ کے کام سنبھال رہے ہیں۔ مجھے سکون سے ساتھ بیٹھ کر بات کرنا یاد آتا ہے۔ کیا ہم اس ہفتے آدھا گھنٹہ صرف ایک دوسرے کے لیے رکھ سکتے ہیں؟",
    },
}


# Keep the initial launch set readable in this file while loading the larger
# bilingual library from a separate content module.
from seo_expansion import ADDITIONAL_TOPICS, ADDITIONAL_URDU_TOPICS

TOPICS.update(ADDITIONAL_TOPICS)
URDU_TOPICS.update(ADDITIONAL_URDU_TOPICS)

# Every English guide now has a matching Urdu guide and reciprocal hreflang.
for urdu_slug, urdu_topic in URDU_TOPICS.items():
    TOPICS[urdu_topic["english"]]["urdu"] = urdu_slug
